# .github/workflows/build.yml
name: Build and Release Electron App

on:
  workflow_dispatch: # Allow manual triggering
  push:
    branches: [main]
    tags: ['v*.*.*'] # Trigger on version tags like v1.0.0 (more specific)
  pull_request:
    branches: [main]

# Cancel redundant builds on PR pushes
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # 1. Validate Code (Quick check on Ubuntu)
  validate:
    name: Validate Code (Lint & Build Frontend)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20 # Match your project's Node version
          cache: 'npm'

      - name: Install Dependencies (Ignoring Scripts)
        run: npm ci --ignore-scripts
        env:
          NPM_CONFIG_IGNORE_SCRIPTS: 'true'

      - name: Lint Code
        run: npm run lint:strict # Fail build on lint errors

      - name: Build Frontend (Vite)
        run: npm run build # Assumes 'vite build'

  # 2. Build macOS App
  build_macos:
    name: Build and Release macOS
    needs: validate
    # Only run full build/release on tag push or manual dispatch
    if: startsWith(github.ref, 'refs/tags/v') || github.event_name == 'workflow_dispatch'
    runs-on: macos-latest
    env:
      # --- Build Flags (macOS uses clang, respects CXXFLAGS) ---
      CXXFLAGS: --std=c++20
      # --- Signing & Notarization Secrets ---
      CSC_LINK: ${{ secrets.CSC_LINK }}
      CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
      APPLE_ID: ${{ secrets.APPLE_ID }}
      APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
      APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
      # --- Electron Builder Config ---
      CSC_IDENTITY_AUTO_DISCOVERY: true
      # --- GitHub Token ---
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Dependencies (includes postinstall)
        # Env flags from job level (CXXFLAGS) should be inherited
        run: npm ci

      - name: Rebuild Native Modules for Electron
        # Ensure this script correctly uses @electron/rebuild
        # It inherits CXXFLAGS from the job env
        run: npm run rebuild-native-modules --verbose

      - name: Build Frontend (Vite)
        run: npm run build

      - name: Package macOS Application
        # mac-build.js should primarily call 'npx electron-builder --mac'
        run: node scripts/mac-build.js --verbose

      - name: List Build Output
        run: ls -lR release-builds

      - name: Upload macOS Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macos-build-${{ github.ref_name }}
          path: |
            release-builds/**/*.dmg
            release-builds/**/*.zip
          if-no-files-found: error # Fail if build didn't produce expected output

      - name: Create GitHub Release and Upload macOS Assets
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            release-builds/**/*.dmg
            release-builds/**/*.zip
          name: ${{ github.ref_name }} # Use tag name as release name
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Explicitly passed

  # 3. Build Windows App
  build_windows:
    name: Build and Release Windows
    needs: validate
    if: startsWith(github.ref, 'refs/tags/v') || github.event_name == 'workflow_dispatch'
    runs-on: windows-latest
    env:
      # --- Build Flags for node-gyp & MSVC ---
      GYP_MSVS_VERSION: 2022    # Env var node-gyp uses directly
      CXXFLAGS: /std:c++20       # MSVC flag for C++20 (also passed explicitly below)
      # PYTHON is set dynamically in steps
      # --- GitHub Token ---
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Set up Python for node-gyp
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Set PYTHON Environment Variable for node-gyp
        run: echo "PYTHON=${{ env.pythonLocation }}\python.exe" | Out-File -FilePath $env:GITHUB_ENV -Append
        shell: pwsh

      - name: Setup MSVC Developer Command Prompt environment
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64 # Target x64 builds

      - name: Configure npm for Windows Build (BEFORE Install)
        # Set valid npm config keys. Avoid invalid ones.
        run: |
          npm config set msvs_version 2022 --location=project
          npm config set python "${{ env.PYTHON }}" --location=project
          Write-Host "---- Current npm config ----"
          npm config list -l
          Write-Host "---- Env Vars for Build ----"
          Write-Host "PYTHON=${{ env.PYTHON }}"
          Write-Host "GYP_MSVS_VERSION=${{ env.GYP_MSVS_VERSION }}"
          Write-Host "CXXFLAGS=${{ env.CXXFLAGS }}"
        shell: pwsh

      - name: Install Dependencies (without scripts)
        # Skip postinstall scripts to avoid premature native module rebuilding
        run: npm ci --ignore-scripts
        env:
          PYTHON: ${{ env.PYTHON }}
          GYP_MSVS_VERSION: ${{ env.GYP_MSVS_VERSION }}
          CXXFLAGS: ${{ env.CXXFLAGS }}

      - name: Log Environment Variables before rebuild
        run: |
          echo "Node Version: $(node --version)"
          echo "NPM Version: $(npm --version)"
          echo "Python Path: $(where python)"
          echo "Python Version: $(python --version)"
          echo "CXXFLAGS: ${{ env.CXXFLAGS }}"
          echo "GYP_MSVS_VERSION: ${{ env.GYP_MSVS_VERSION }}"
          echo "Path: $env:Path"
        shell: pwsh

      - name: Rebuild Native Modules for Electron
        # Explicitly run the rebuild script after installation
        run: npm run rebuild-native-modules --verbose
        env:
          PYTHON: ${{ env.PYTHON }}
          GYP_MSVS_VERSION: ${{ env.GYP_MSVS_VERSION }}
          CXXFLAGS: ${{ env.CXXFLAGS }}

      - name: Build Frontend (Vite)
        run: npm run build

      - name: Package Windows Application
        # Ensure windows-build.js passes env vars if it calls electron-builder directly
        run: node scripts/windows-build.js --verbose
        env:
          PYTHON: ${{ env.PYTHON }}
          GYP_MSVS_VERSION: ${{ env.GYP_MSVS_VERSION }}
          CXXFLAGS: ${{ env.CXXFLAGS }}

      - name: List Build Output
        run: Get-ChildItem -Recurse release-builds | Select-Object FullName, Length | Format-Table -AutoSize
        shell: pwsh

      - name: Upload Windows Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-build-${{ github.ref_name }}
          path: release-builds/**/*.exe # Upload both setup and portable
          if-no-files-found: error # Fail if build didn't produce expected output

      - name: Upload Windows Assets to Existing Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v2
        with:
          files: release-builds/**/*.exe
          # Reuse the release created by the macOS job
          # Ensure tag name matches if release is auto-created by mac job
          tag_name: ${{ github.ref_name }}
          draft: false
          prerelease: false
          generate_release_notes: false # Prevent overwriting notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Explicitly passed