name: Build and Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest]  # Focusing on macOS for now

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"

      - name: Install dependencies
        run: |
          npm install --legacy-peer-deps
          npm list electron electron-builder || true

      - name: Cache electron-builder
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/electron
            ~/.cache/electron-builder
          key: ${{ runner.os }}-electron-builder-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-electron-builder-

      # Code signing setup for macOS
      - name: Import macOS certificates
        if: matrix.os == 'macos-latest' && startsWith(github.ref, 'refs/tags/')
        env:
          MACOS_CERTIFICATE: ${{ secrets.MACOS_CERTIFICATE }}
          MACOS_CERTIFICATE_PWD: ${{ secrets.MACOS_CERTIFICATE_PWD }}
          KEYCHAIN_PWD: ${{ secrets.KEYCHAIN_PWD || 'tempkeychain' }}
        run: |
          # Create temporary keychain
          security create-keychain -p "$KEYCHAIN_PWD" build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "$KEYCHAIN_PWD" build.keychain
          
          # Import certificate to keychain
          echo "$MACOS_CERTIFICATE" | base64 -D > certificate.p12
          security import certificate.p12 -k build.keychain -P "$MACOS_CERTIFICATE_PWD" -T /usr/bin/codesign
          
          # Add keychain to keychain-list
          security list-keychains -s build.keychain
          security set-keychain-settings -t 3600 -l build.keychain
          
          # Allow codesign to access keychain
          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k "$KEYCHAIN_PWD" build.keychain
          
          # Verify certificate import
          security find-identity -v -p codesigning build.keychain

      - name: Build Vite app
        run: npm run build
        env:
          CI: true

      - name: Build for macOS
        if: matrix.os == 'macos-latest'
        run: |
          # Debug info
          echo "Current directory: $(pwd)"
          echo "Directory contents:"
          ls -la
          echo "Dist directory contents:"
          ls -la dist || echo "No dist directory"
          
          # Run the build with verbose logging
          npm run package:mac --verbose
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CSC_LINK: ${{ secrets.MACOS_CERTIFICATE }}
          CSC_KEY_PASSWORD: ${{ secrets.MACOS_CERTIFICATE_PWD }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
          DEBUG: electron-builder,electron-builder:*

      - name: Verify build output
        run: |
          echo "Release builds directory contents:"
          ls -la release-builds || echo "No release-builds directory"
          find . -name "*.dmg" -o -name "*.zip"

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macos-artifacts
          path: |
            release-builds/*.dmg
            release-builds/*.zip
          if-no-files-found: error

      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            release-builds/*.dmg
            release-builds/*.zip
          draft: true
          generate_release_notes: true
          fail_on_unmatched_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
